### PR TITLE
Add egg selection when creating server via store

### PR DESCRIPTION
**Pull request by devilAPI**

### CODE REVIEW

**Comment by devilAPI** [comment]
image

**Comment by camwhi-te** [comment]
How will people be able to know what the Egg ID's are?
The best way of doing this is to probably make a dropdown for all available eggs so users can select it.
If you need help with this, let me know.

**Comment by camwhi-te** [comment]
Another note: The backend will need to be adjusted for this but I'm able to add that, so no big deal.

**Comment by devilAPI** [comment]
> How will people be able to know what the Egg ID's are? The best way of doing this is to probably make a dropdown for all available eggs so users can select it. If you need help with this, let me know.

yes, i was planning on implementing that, unfortunately im new to modding pterodactyl and im pretty confused about its api, so help would be great

**Comment by devilAPI** [comment]
i was also planning on a toggle on the settings tab (so you can also use a "default egg" option, if youre a fan of eggactyl)

**Comment by TheFallenSpirit** [comment]
In order for this to work, a toggle would need to be added to all eggs, simply a true false to show or not to show the egg. Then you would fetch all the eggs from the backend and filter the ones that are "enabled". If you need any help with this let me know I can help.

**Pull request closed without merging**
